[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[override]]
  branch = "master"
  name = "google.golang.org/api"

[[override]]
  branch = "master"
  name = "golang.org/x/net"